INSERT INTO `Tables` (table_number, number_of_chairs, status) VALUES
(1, 4, 'not occupied'),
(2, 2, 'not occupied'),
(3, 6, 'not occupied'),
(4, 4, 'occupied'),
(5, 2, 'not occupied'),
(6, 4, 'occupied'),
(7, 6, 'not occupied'),
(8, 4, 'occupied'),
(9, 2, 'not occupied'),
(10, 4, 'occupied'),
(11, 6, 'not occupied'),
(12, 2, 'occupied'),
(13, 4, 'not occupied'),
(14, 6, 'occupied'),
(15, 2, 'occupied'),
(16, 4, 'occupied'),
(17, 6, 'occupied'),
(18, 4, 'occupied'),
(19, 2, 'not occupied'),
(20, 6, 'occupied');
